server.port=8090

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://database-sistemadeviajes.cn2giyugy8sv.us-east-2.rds.amazonaws.com:3306/database-sistemadeviajes?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root1234567
